spring.application.name=prac

server.port=8080

spring.data.mongodb.uri=mongodb+srv://iamarnavtyagig_db_user:arnav%232006@auth.qmn5a4e.mongodb.net/authdb?retryWrites=true&w=majority&appName=auth
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=b0b660001@smtp-brevo.com
spring.mail.password=xsmtpsib-4c13c9d9b8658319d15826765fc1d1dde124b347942acf7258fef86da7c3a4d4-RqNqyvcmIkzBlqzr

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
