
spring.application.name=prac

server.port=8080

spring.data.mongodb.uri=mongodb+srv://iamarnavtyagig_db_user:arnav%232006@auth.qmn5a4e.mongodb.net/authdb?retryWrites=true&w=majority&appName=auth
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arnavtyagibhai@gmail.com
spring.mail.password=lwnt eopg ikhy kxtv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

